"""Echo agent generated by Emergence CLI."""
import json, sys

def handle(msg: dict) -> dict:
    """Very first prototype — just echoes HELP prompts."""
    if msg.get("verb") == "HELP":
        return {
            "id": msg["id"],
            "from": "demo-pub",
            "to": msg["from"],
            "verb": "DONE",
            "data": {"echo": msg["data"]}
        }
    raise ValueError("Unsupported verb")

if __name__ == "__main__":
    incoming = json.load(sys.stdin)
    json.dump(handle(incoming), sys.stdout)
